version: "3.9"

services:
  portafolio:
    image: ghcr.io/darrauthstudent/portafolio:latest
    container_name: portafolio_app
    restart: unless-stopped

    ports:
      - "4321:4321"

    environment:
      HOST: 0.0.0.0
      PORT: 4321
      NODE_ENV: production
